javascript_compressor: closure

javascripts:
  application:
    - public/javascripts/app/controls.js
    - public/javascripts/app/application.js

stylesheets:
  application:
    - public/stylesheets/common.css
    - public/stylesheets/application.css
